export const SET_FILES_INITIAL_STATE = "SET_FILES_INITIAL_STATE";

export const UPLOAD_FILES = "UPLOAD_FILES";
export const UPLOAD_FILES_PROGRESS = "UPLOAD_FILES_PROGRESS";
export const UPLOAD_FILES_SUCCESS = "UPLOAD_FILES_SUCCESS";
export const UPLOAD_FILES_ERROR = "UPLOAD_FILES_ERROR";
export const UPLOAD_FILES_PAUSE = "UPLOAD_FILES_PAUSE";
export const SET_UPLOAD_FILES_PAUSE = "SET_UPLOAD_FILES_PAUSE";
export const UPLOAD_FILES_RESUME = "UPLOAD_FILES_RESUME";
export const SET_UPLOAD_FILES_RESUME = "SET_UPLOAD_FILES_RESUME";
export const UPLOAD_FILES_CANCEL = "UPLOAD_FILES_CANCEL";
export const SET_UPLOAD_FILES_INITIAL_STATE = "SET_UPLOAD_FILES_INITIAL_STATE";


export const LIST_FILES_LOADING = "LIST_FILES_LOADING";
export const LIST_FILES_SUCCESS = "LIST_FILES_SUCCESS";
export const LIST_FILES_ERROR = "LIST_FILES_ERROR";
export const SET_LIST_FILES_INITIAL_STATE = "SET_LIST_FILES_INITIAL_STATE";

export const DELETE_FILES = "DELETE_FILES";
export const DELETE_FILES_LOADING = "DELETE_FILES_LOADING";
export const DELETE_FILES_SUCCESS = "DELETE_FILES_SUCCESS";
export const DELETE_FILES_ERROR = "DELETE_FILES_ERROR";
export const SET_DELETE_FILES_INITIAL_STATE = "SET_DELETE_FILES_INITIAL_STATE";