export const SET_POSTS_INITIAL_STATE = "SET_POSTS_INITIAL_STATE";

export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_LOADING = "CREATE_POST_LOADING";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";
export const SET_CREATE_POST_INITIAL_STATE = "SET_CREATE_POST_INITIAL_STATE";

export const LIST_POSTS = "LIST_POSTS";
export const LIST_POSTS_LOADING = "LIST_POSTS_LOADING";
export const LIST_POSTS_SUCCESS = "LIST_POSTS_SUCCESS";
export const LIST_POSTS_ERROR = "LIST_POSTS_ERROR";
export const SET_LIST_POSTS_INITIAL_STATE = "SET_LIST_POSTS_INITIAL_STATE";

export const GET_POST = "GET_POST";
export const GET_POST_LOADING = "GET_POST_LOADING";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_ERROR = "GET_POST_ERROR";
export const GET_POST_REDIRECT = "GET_POST_REDIRECT";
export const SET_GET_POST_INITIAL_STATE = "SET_GET_POST_INITIAL_STATE";

export const SET_EDIT_POST_DATA = "SET_EDIT_POST_DATA";
export const EDIT_POST = "EDIT_POST";
export const EDIT_POST_LOADING = "EDIT_POST_LOADING";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_ERROR = "EDIT_POST_ERROR";
export const SET_EDIT_POST_INITIAL_STATE = "SET_EDIT_POST_INITIAL_STATE";

export const SET_DELETE_POST_DATA = "SET_DELETE_POST_DATA";
export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_LOADING = "DELETE_POST_LOADING";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_ERROR = "DELETE_POST_ERROR";
export const SET_DELETE_POST_INITIAL_STATE = "SET_DELETE_POST_INITIAL_STATE";

export const GET_POST_USER = "GET_POST_USER";
export const SET_POST_USER = "SET_POST_USER";